name: CI

on: push

jobs:
    main:
        runs-on: ubuntu-latest
        name: Run CI
        steps:
            - name: Cloning repo
              uses: actions/checkout@v2.3.5

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: 16

            - name: Install dependencies
              uses: bahmutov/npm-install@v1.6.0

            - name: ESLint
              run: >
                  npm run lint

            - name: Build project
              run: >
                  npm run build:all